version: '3.6'
#====================
#（★）服务
#====================
services:
  study-springcloud-docker:
    #（▲）镜像
    image: 114.67.102.8:5000/study/study-springboot-docker:1
    #（▲）端口
    #expose: ""
    ports:
      - "7000:7000"
    #（▲）数据卷
    volumes:
      - /xdfapp:/xdfapp
    #（▲）环境变量
    environment:
      - NAME=wangzhj
      - AGE=21
    #（▲）日志服务
    #    logging:
    #      driver: "json-file"
    #      options:
    #        max-size: "100m"
    #        max-file: "3"
    #（▲）网络
    #network_mode:
    networks:
      - overlay_net
    #（▲）
    #command: tail -f /dev/null
    #（▲）工作目录
    #working_dir: /
    #（▲）部署
#    deploy:
#      model: global
#      replicas: 3
#      restart_policy:
#        condition: restart
#        delay:  2
#        max_attemps: 3
#        windows: 3
#====================
#（★）网络
#====================
networks:
  overlay_net:
    external: true
  briage_net:
    driver: briage